version: '3.8'
services:
  node:
    build: .
    restart: always
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    environment:
        PORT: ${PORT}
        CHOKIDAR_USEPOLLING: ${CHOKIDAR_USEPOLLING}
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
    networks:
      - my-custom-network
  postgres:
    build: ./database/
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./database/data:/var/lib/postgresql/data
    networks:
      - my-custom-network
networks:
  my-custom-network:
    driver: bridge